# Generated by Django 4.1.1 on 2022-12-17 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from ..models import ProjectApplication
from account.models import User


def test_data(apps, schema_editor):
    ProjectApplication.objects.create(
        title="Название проекта 1",
        status='SELECTION_PROCESS',
        work_type='PREP',
        deadline_from='2022-01-21',
        deadline_to='2022-02-21',
        description='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.',
        budget_from=1000,
        budget_to=500_000,
        tasks=['Задача 1', 'Задача 2'],
        owner=User.objects.get(pk=3)
    )
    ProjectApplication.objects.create(
        title="Название проекта 2",
        status='FINISHED',
        work_type='GEOD',
        deadline_from='2022-01-21',
        deadline_to='2022-02-21',
        description='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.',
        budget_from=1000,
        budget_to=500_000,
        owner=User.objects.get(pk=3)
    )
    ProjectApplication.objects.create(
        title="Название проекта 3",
        status='DRAFT',
        work_type='ZEM',
        deadline_from='2022-01-21',
        deadline_to='2022-02-21',
        description='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.',
        budget_from=1000,
        budget_to=500_000,
        owner=User.objects.get(pk=3)
    )
    ProjectApplication.objects.create(
        title="Название проекта 4",
        status='PERFORMER_APPOINTED',
        work_type='UST',
        deadline_from='2022-01-21',
        deadline_to='2022-02-21',
        description='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.',
        budget_from=1000,
        budget_to=500_000,
        owner=User.objects.get(pk=3)
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('work_type', models.CharField(choices=[('PREP', 'Подготовительные'), ('GEOD', 'Геодезические'), ('ZEM', 'Земляные'), ('UST', 'Устройство скважин'), ('SWAI', 'Свайные работы. Крепление грунтов'), ('ZBI', 'Устройство бетонных и железнобетонных монолитных конструкций'), ('MON', 'Монтаж сборных бетонных и железнобетонных конструкций'), ('BOM', 'Буровзрывные работы при строительстве')], max_length=255, verbose_name='Вид работ')),
                ('deadline_from', models.DateField(verbose_name='Дата начала работ')),
                ('deadline_to', models.DateField(verbose_name='Дата окончания работ')),
                ('budget_from', models.IntegerField(verbose_name='Старт бюджета')),
                ('budget_to', models.IntegerField(verbose_name='Лимит бюджета')),
                ('tasks', models.JSONField(default=list, verbose_name='Список задач')),
                ('status', models.CharField(choices=[('DRAFT', 'Проект заявки'), ('SELECTION_PROCESS', 'Осуществляется набор'), ('PERFORMER_APPOINTED', 'Исполнитель назначен'), ('FINISHED', 'Завершенные')], max_length=255, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(test_data)
    ]
